### ISSUE TITLE
Allow to use custom LocalePersistor

### ISSUE THREAD

**Issue by alexeyvasilyev** [franmontiel/LocaleChanger#2]
There are two problems with current LocalePersistor:

1. At the moment LocalePreference uses LocalePersistor.class.getPackage().getName() as SharedPreference name. The problem is that if you use Proguard this class name can be different. So in the next app update there is a high probability that desired shared preference name will not exists.

2. Another problem is that there is no way to specify your own storage (e.g. I do not want to have any storage in LocalChanger library, I have my own storage in the app).

It would be really useful if it would be possible to use custom LocalePersistor.

**Comment by franmontiel** [comment]
Hi @alexeyvasilyev,
1. Yes you're right. I need to test the library with Poguard enabled an create the appropriate rules to avoid those kind of problems.
2. There should be pretty straightforward to create an interface for the Persistor. I need think about how to deal with the initialization of the library in this case because I don't want to create a lot of different initializers. Maybe I will pass a Builder object to the initialize method.

**Comment by alexeyvasilyev** [comment]
Builder is a nice idea.

**Comment by franmontiel** [comment]
I've published a new update(0.9.1) fixing the first problem and now the SharedPreferences file name does not depend on package structure. As you pointed out it will be very useful to avoid Proguard related issues but also it will allow the package to change in the future without losing access to the file.

Concerning the custom Persistor I don't have much time to do it right now but feel free to make PR. It is needed to create an interface for the Persistor and also make the load method to use a callback to return the results (to allow the implementations to be executed in a non-UI thread).

**Comment by franmontiel** [comment]
Closed due to inactivity
